### ISSUE TITLE
JOverflow parser exception when calling `idAsString` on a `JavaHeapObject`

### ISSUE THREAD

**Issue by tabjy** [tabjy/jmc#2]
The exact steps to reproduce is yet unknown.

```
java.util.concurrent.CompletionException: java.lang.ArrayIndexOutOfBoundsException: arraycopy: source index -84166782 out of bounds for byte[26214400]
	at java.base/java.util.concurrent.CompletableFuture.encodeThrowable(CompletableFuture.java:314)
	at java.base/java.util.concurrent.CompletableFuture.completeThrowable(CompletableFuture.java:319)
	at java.base/java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1702)
	at java.base/java.util.concurrent.CompletableFuture$AsyncSupply.exec(CompletableFuture.java:1692)
	at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:290)
	at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1020)
	at java.base/java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1656)
	at java.base/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1594)
	at java.base/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:177)
Caused by: java.lang.ArrayIndexOutOfBoundsException: arraycopy: source index -84166782 out of bounds for byte[26214400]
	at org.openjdk.jmc.joverflow.heap.parser.CachedReadBuffer.get(CachedReadBuffer.java:226)
	at org.openjdk.jmc.joverflow.heap.parser.CachedReadBuffer.getLong(CachedReadBuffer.java:259)
	at org.openjdk.jmc.joverflow.heap.model.JavaLazyReadObject.readId(JavaLazyReadObject.java:127)
	at org.openjdk.jmc.joverflow.heap.model.JavaLazyReadObject.readId(JavaLazyReadObject.java:119)
	at org.openjdk.jmc.joverflow.heap.model.JavaHeapObject.idAsString(JavaHeapObject.java:88)
	at org.openjdk.jmc.joverflow.ui.viewers.TreeMapViewer$1.buildTree(TreeMapViewer.java:56)
	at org.openjdk.jmc.joverflow.ui.viewers.TreeMapViewer$1.buildTree(TreeMapViewer.java:59)
	at org.openjdk.jmc.joverflow.ui.viewers.TreeMapViewer$1.buildTree(TreeMapViewer.java:59)
	at org.openjdk.jmc.joverflow.ui.viewers.TreeMapViewer$1.buildTree(TreeMapViewer.java:70)
	at org.openjdk.jmc.joverflow.ui.viewers.TreeMapViewer$1.buildTree(TreeMapViewer.java:59)
	at org.openjdk.jmc.joverflow.ui.viewers.TreeMapViewer$1.buildTree(TreeMapViewer.java:59)
	at org.openjdk.jmc.joverflow.ui.viewers.TreeMapViewer$1.buildTree(TreeMapViewer.java:70)
	at org.openjdk.jmc.joverflow.ui.viewers.TreeMapViewer$1.buildTree(TreeMapViewer.java:59)
	at org.openjdk.jmc.joverflow.ui.viewers.TreeMapViewer$1.buildModel(TreeMapViewer.java:39)
	at java.base/java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1700)
	... 6 more
```

It is currently unclear if this issue is related to [JMC-6082](https://bugs.openjdk.java.net/browse/JMC-6082) and the [corresponding patch](http://hg.openjdk.java.net/jmc/jmc/rev/76af4214ed3a).

**Comment by tabjy** [comment]
update:

Turning `DEBUG = true` triggers `checkListConsistency()` to execute, with failed assertions.

```
java.util.concurrent.CompletionException: java.lang.Error: In-heap file cache internal error: listSize = 49
page = Page 24, idxInFile = 177, previous = 41, next = null
LRU = Page 12, idxInFile = 139, previous = null, next = 34;  MRU = Page 24, idxInFile = 177, previous = 41, next = null
, numPagesInPool = 50
	at java.base/java.util.concurrent.CompletableFuture.encodeThrowable(CompletableFuture.java:314)
	at java.base/java.util.concurrent.CompletableFuture.completeThrowable(CompletableFuture.java:319)
	at java.base/java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1702)
	at java.base/java.util.concurrent.CompletableFuture$AsyncSupply.exec(CompletableFuture.java:1692)
	at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:290)
	at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1020)
	at java.base/java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1656)
	at java.base/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1594)
	at java.base/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:177)
Caused by: java.lang.Error: In-heap file cache internal error: listSize = 49
page = Page 24, idxInFile = 177, previous = 41, next = null
LRU = Page 12, idxInFile = 139, previous = null, next = 34;  MRU = Page 24, idxInFile = 177, previous = 41, next = null
, numPagesInPool = 50
	at org.openjdk.jmc.joverflow.heap.parser.CachedReadBuffer.assertTrue(CachedReadBuffer.java:387)
	at org.openjdk.jmc.joverflow.heap.parser.CachedReadBuffer.checkListConsistency(CachedReadBuffer.java:382)
	at org.openjdk.jmc.joverflow.heap.parser.CachedReadBuffer.get(CachedReadBuffer.java:208)
	at org.openjdk.jmc.joverflow.heap.parser.CachedReadBuffer.getLong(CachedReadBuffer.java:276)
	at org.openjdk.jmc.joverflow.heap.model.JavaLazyReadObject.readId(JavaLazyReadObject.java:127)
	at org.openjdk.jmc.joverflow.heap.model.JavaLazyReadObject.readId(JavaLazyReadObject.java:119)
	at org.openjdk.jmc.joverflow.heap.model.JavaHeapObject.idAsString(JavaHeapObject.java:88)
	at org.openjdk.jmc.joverflow.ui.viewers.TreeMapViewer$1.buildTree(TreeMapViewer.java:44)
	at org.openjdk.jmc.joverflow.ui.viewers.TreeMapViewer$1.buildModel(TreeMapViewer.java:39)
	at java.base/java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1700)
	... 6 more
```

**Comment by tabjy** [comment]
Potential cause:

There have been cases like:
```java
	...
	checkListConsistency(page);                               // no exception raised
	// Update the linked list
	if (page != mostRecentlyUsed) {
		if (DEBUG) {
			checkListConsistency(page);               // assertion failed
		}
        ...
```

It is clear the two if statements are side-effect free. Since CachedReadBuffer is not designed to be concurrent safe, there must be an interruption between the two assertions, which atomicity is broken.

Although in the UI controller, a tree model is built using a single-threaded CompletableFuture, according to [documentation](https://docs.oracle.com/javase/8/docs/api/java/util/concurrent/CompletableFuture.html#cancel-boolean-) on `CompletableFuture:cancel(boolean mayInterruptIfRunning)`, "`mayInterruptIfRunning` has no effect in this implementation because interrupts are not used to control processing."

Forcing `CachedReadBuffer:get(long pos, byte[] buf, int numBytesToRead)` to be atomic by adding `synchronized` keyword does resolve the issue, but this involves changing codes in another module and should be avoided if possible.
